### ISSUE TITLE
Improve documentation example

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/ParamTools#120]
I've been thinking a lot about good examples for ParamTools. Here are a couple things on my mind:
- The "10 minutes to pandas" example just uses a few columns A, B, C, D; numpy arrays with random values; and a date index: https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
- X-Array has a toy weather example that is probably targeted to its initial and probably still primary audience of climatologists/geodata people: http://xarray.pydata.org/en/stable/examples/weather-data.html
- I built a toy tax calculator for my pydata talk that demonstrates paramtools concepts fairly well: https://github.com/hdoupe/pydata2020/blob/main/Simple%20tax%20calculator.ipynb

My dilemma: Should I use a super simple example like the pandas one or should I add some context to give the example a more practical feel like my simple tax calculator example?

I'm worried that non-tax modeling folks will be as confused as I am when I'm trying to understand the supposedly simple toy example in the x-array docs.

**Comment by jdebacker** [comment]
@hdoupe I like the simple example.  I agree that requiring domain-specific knowledge maybe a hurdle.  

And perhaps with your simple example to work from, other projects and show similar examples of how parameters are handled in their specific contexts.

**Comment by hdoupe** [comment]
Thanks @jdebacker. The more I look at this 10 minutes to pandas doc, the more I think this could be a good model for ParamTools. The examples they use are good. The way they introduce the concepts is nice too:

- how do you create a dataframe
- how do you view your data
- how do you query your data
- how do you update your data
- how do you do operations on your data
