### ISSUE TITLE
Boolean validators

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/ParamTools#126]
@hdoupe . I am adding a Boolean parameter to [OG-USA](https://github.com/PSLmodels/OG-USA) in [PR #715](https://github.com/PSLmodels/OG-USA/pull/715). I have two questions about the validators for this parameter in our [`default_parameters.json`](https://github.com/rickecon/OG-USA/blob/ubi_code/ogusa/default_parameters.json) file in the [`ubi_growthadj`](https://github.com/rickecon/OG-USA/blob/ubi_code/ogusa/default_parameters.json#L787) parameter. I couldn't find the answer to either of these questions in the documentation.

1. Does ParamTools treat Booleans differently than Python does? I noticed that for all of our Boolean parameters in OG-USA's [`default_parameters.json`](https://github.com/rickecon/OG-USA/blob/ubi_code/ogusa/default_parameters.json) file, the Boolean value is set to either lower-case "true" or lower-case "false". 
    ```
    "value": false
    ```
    or
    ```
    "value": true
    ```
    This differs from how Python receives Booleans as non-string (or `bool`) objects written `True` and `False`, with the first letter capitalized. Are the ParamTools Boolean values strings? If so, are they case sensitive (they should be)?

2. What is the correct format for Boolean parameter "validators"? Is this the same as any discrete set of valid parameter values? If so, I did find the following option in a non-Boolean example in the ParamTools documentation. The following are two possibilities in my mind (related to my first question).
    ```
    "validators": {"choice": {"choices": ["true", "false"]}}
    ```
    or
    ```
    "validators": {"choice": {"choices": [True, False]}}
    ```

**Comment by jdebacker** [comment]
@rickecon JSON format uses lower case for true/false.

You can see an example of how to validate booleans in the OG-USA default parameters [here](https://github.com/PSLmodels/OG-USA/blob/218d94a6f7d42a319f73dfd2893962166ec09e50/ogusa/default_parameters.json#L2634).

**Comment by jdebacker** [comment]
Ah - I see my above example is more complex because it is for a conditional validator.  But your first example of how the validator should be formatted is the way to go.

**Comment by rickecon** [comment]
Thanks, @jdebacker. I think I need that conditional validator anyway. Thanks for the example from my own repo :)

**Comment by rickecon** [comment]
@jdebacker How would you code up the `"validators"` part of the `ubi_growthadj` parameter in OG-USA's `default_parameters.json` with the following validation condition?
```
if g_y_annual < 0, then ubi_growthadj must equal true

otherwise ubi_growthadj in [true, false]
```
The `"otherwise"` part is clear from our `"when"` example above, but how do I handle the inequality condition forcing a `true` value?

**Comment by jdebacker** [comment]
@rickecon: see [here](https://github.com/PSLmodels/ParamTools/blob/cde06c5ca455b845bed35268d96066597707a5a2/docs/parameters.md)

You'll have something like:

```
    "test_parameter": {
        "title": "test parameter",
        "description": "test parameter",
        "section_1": "test parameter",
        "section_2": "test parameter",
        "notes": "",
        "type": "bool",
        "value": [
            {
                "value": true
            }
        ],
        "validators": {
            "when": {
                "param": "g_y_annual",
                "is": {"less_than": 0},
                "then": {"choice": {"choices": [true]}},
                "otherwise": {"choice": {"choices": [true, false]}}
            }
        }
    },
```

**Comment by rickecon** [comment]
@jdebacker . I love it. We should put some instructions like these in the ParamTools documentation for the full functionality of the validators. Or point me to where that is in the documentation @hdoupe. What a great tool!

**Comment by hdoupe** [comment]
Hey @rickecon and @jdebacker thanks for opening (and resolving) this issue.

The conditional validator is briefly shown here in the docs: https://paramtools.dev/parameters.html#members

I think a simple example to explain and demonstrate how conditional validators work in the ["Guide" section of the docs](https://paramtools.dev/api/guide.html) would be helpful. I like @jdebacker's example:
```json
    "test_parameter": {
        "title": "test parameter",
        "description": "test parameter",
        "section_1": "test parameter",
        "section_2": "test parameter",
        "notes": "",
        "type": "bool",
        "value": [
            {
                "value": true
            }
        ],
        "validators": {
            "when": {
                "param": "g_y_annual",
                "is": {"less_than": 0},
                "then": {"choice": {"choices": [true]}},
                "otherwise": {"choice": {"choices": [true, false]}}
            }
        }
    },
```

I may make some minor modifications like using `a` and `b` parameters kind of like this guide: https://paramtools.dev/api/viewing-data.html


> @hdoupe. What a great tool!

Thanks Rick!
