### ISSUE TITLE
Are there plans for a paramtools conda package?

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/ParamTools#20]
Wouldn't this make it easier for people who are familiar with downloading packages from PSLmodels?

**Comment by hdoupe** [comment]
Yes, I think you are right. Pip makes it very easy to release pure Python packages. You only need two commands to release a package and it works on all OS's:

```bash
python setup.py sdist bdist_wheel
twine upload dist/*
```

However, I agree that making it conda install-able would provide a standard installation experience for PSLmodels users.

What do I need to do to release ParamTools with Package-Builder?

**Comment by hdoupe** [comment]
I'm also planning to make NumPy a hard dependency of ParamTools. Conda provides a much more reliable NumPy installation experience than pip. So, that's another good reason to have a conda ParamTools package.

**Comment by martinholmer** [comment]
@hdoupe asked:
> What do I need to do to release ParamTools with Package-Builder?

Read this [Package-Builder documentation](https://github.com/PSLmodels/Package-Builder#using-package-builders-pbrelease-tool).  If you have any remaining questions, ask them here in the issue #20 conversation.

**Comment by hdoupe** [comment]
Ok, thanks @martinholmer.

**Comment by hdoupe** [comment]
Closed via #41. Thanks for bringing this up. Also, @martinholmer Package-Builder is awesome. Your recent improvements to that package made this process easy and painless.

**Comment by martinholmer** [comment]
@hdoupe said in ParamTools issue #20:
> Package-Builder is awesome. Your recent improvements to that package made this process easy and painless.

Well, thanks.  But most of the credit goes to you as I just followed the logical outline of what you had done in your earlier script.  I've tried to make that clear in the historical record in the Package-Builder repository.

**Comment by hdoupe** [comment]
Ha! Well, I didn't leave it in the polished up state that it's in now. I'm glad we have a nice package builder.
