### ISSUE TITLE
Simplifying changes

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/ParamTools#43]
Proposed changes:

- Drop `schema.json`, and move it into a top-level `schema` member. (#49)

  - Some users have asked why there need to be two files. I thought it was nice to define the space of the parameters separately from the actual parameters. However, it seems to be more intuitive to just have one file. Further, ParamTools would have a smaller footprint if just one configuration file was required.

- Rename `dims` to `selectors`. (#47)

  - I can sense people's eyes glazing over every time they read or hear "space" or "dimension." Let's make this idea more intuitive and rename "dimension" to something like "selector." Essentially, the user wants to select all or a subset of a parameter's value(s). The parameters that are used in this select operation are called "selectors." I also considered "labels" instead of "dimensions." I'm open to other names for these selector parameters.
   [EDIT: I chose `label` instead of `selector`. See #47 for more information]

- Rename `optional`—>`additional_members`. (#49)

- Set a default value of zero for `number_dims` . (#44)

  - With this change, users only have to specify `number_dims` in the rare cases in which it's greater than zero.

- (#45) Make

  ```json
  {
    "myparam": {
      "value": [{"value": "myval"}]
    }
  }
  ```

  equivalent to:

  ```
  {
    "myparam": {
      "value": "myval"
    }
  }
  ```

  The majority of cases are much simpler than the multi-selector cases that ParamTools was built to handle. ParamTools should handle the simple cases well, too. 

  

The config file would look something like this after these proposed changes:

```json
{
    "schema": {
        "selectors": {
            "year": {
                "type": "int",
                "validators": {"range": {"min": 2013, "max": 2027}}
            },
            "marital_status": {
                "type": "str",
                "validators": {"choice": {"choices": ["single", "joint", "separate",
                                                     "headhousehold", "widow"]}}
            },
        },
        "additional_members": {
            "cpi_inflatable": {"type": "bool"},
            "cpi_inflated": {"type": "bool"}
        }
    },
    "standard_deduction": {
        "title": "Standard deduction amount",
        "description": "Amount filing unit can use as a standard deduction.",
        "notes": "",
        "cpi_inflatable": true,
        "cpi_inflated": true,
        "type": "float",
        "value": [
            {"year": 2024, "marital_status": "single", "value": 13673.68},
            {"year": 2024, "marital_status": "joint", "value": 27347.36},
            {"year": 2024, "marital_status": "separate", "value": 13673.68},
            {"year": 2024, "marital_status": "headhousehold", "value": 20510.52},
            {"year": 2024, "marital_status": "widow", "value": 27347.36},
            {"year": 2025, "marital_status": "single", "value": 13967.66},
            {"year": 2025, "marital_status": "joint", "value": 27935.33},
            {"year": 2025, "marital_status": "separate", "value": 13967.66},
            {"year": 2025, "marital_status": "headhousehold", "value": 20951.49},
            {"year": 2025, "marital_status": "widow", "value": 27935.33},
            {"year": 2026, "marital_status": "single", "value": 7690.0},
            {"year": 2026, "marital_status": "joint", "value": 15380.0},
            {"year": 2026, "marital_status": "separate", "value": 7690.0},
            {"year": 2026, "marital_status": "headhousehold", "value": 11323.0},
            {"year": 2026, "marital_status": "widow", "value": 15380.0}],
        "validators": {
            "range": {
                "min": 0,
                "max": 9e+99
            }
        }
    },
    "simple_param": {
        "title": "Simple Param",
        "description": "Demonstrate a very simple parameter",
        "notes": "",
        "cpi_inflatable": true,
        "cpi_inflated": true,
        "type": "float",
        "value": 10.5,
        "validators": {
            "range": {
                "min": 0,
            }
        }
    }
}

```

**Comment by hdoupe** [comment]
@andersonfrailey @MattHJensen @Peter-Metz @martinholmer I'm curious to hear what you think about these changes. If you have any other changes that you'd like to propose, then I'd love to hear them.

**Comment by andersonfrailey** [comment]
>Drop schema.json, and move it into a top-level schema member.

Pro. In my blackjack project where I use ParamTools `schema.json` ended up being a kinda throw away file that I never really figured out how to incorporate into the rest of the project.

>Set a default value of zero for number_dims

Also pro. This would just simplify the process of creating the parameters file.

And big fan of simplifying how values are specified in the configuration file. Overall I'm for all of these changes.

@hdoupe

**Comment by hdoupe** [comment]
Great, thanks for the feedback @andersonfrailey.

**Comment by Peter-Metz** [comment]
I like these changes as well.

In the spirit of simplifying things, I wonder if `notes` should be optional too. I can see certain cases where a note is useful, but my sense is that `description` is sufficient most of the time.

@hdoupe

**Comment by hdoupe** [comment]
Thanks @Peter-Metz. There are a couple other parameters that I intended to use but haven't so far like `out_of_range_minmsg` and `out_of_range_action`. I'll make those optional, too.

**Comment by hdoupe** [comment]
All proposed changes in #43 have been implemented. I've linked to the PR's related to each enhancement in the original issue comment. I'll update the documentation for these changes tomorrow.
