### ISSUE TITLE
More compact `defaults.json`

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/ParamTools#56]
By default, `json.dumps` leaves a lot of white space when printing lists of dictionaries:

```
        "value": [
            {
                "year": 2015,
                "value": 0.35
            },
            {
                "year": 2016,
                "value": 0.35
            },
            {
                "year": 2017,
                "value": 0.35
            },
            {
                "year": 2018,
                "value": 0.21
            },
            {
                "year": 2019,
                "value": 0.21
            },
            {
                "year": 2020,
                "value": 0.21
            },
            {
                "year": 2021,
                "value": 0.21
            },
            {
                "year": 2022,
                "value": 0.21
            },
            {
                "year": 2023,
                "value": 0.21
            },
            {
                "year": 2024,
                "value": 0.21
            },
            {
                "year": 2025,
                "value": 0.21
            },
            {
                "year": 2026,
                "value": 0.21
            },
            {
                "year": 2027,
                "value": 0.21
            },
            {
                "year": 2028,
                "value": 0.21
            }
]
```

This could instead be printed like this:

```
"value": [
    {"year": 2015,"value": 0.35},
    {"year": 2016, "value": 0.35},
    {"year": 2017, "value": 0.35},
    {"year": 2018, "value": 0.21},
    {"year": 2019, "value": 0.21},
    {"year": 2020, "value": 0.21},
    {"year": 2021, "value": 0.21},
    {"year": 2022, "value": 0.21},
    {"year": 2023, "value": 0.21},
    {"year": 2024, "value": 0.21},
    {"year": 2025,"value": 0.21},
    {"year": 2026, "value": 0.21},
    {"year": 2027, "value": 0.21},
    {"year": 2028, "value": 0.21}
],
```

**Comment by jdebacker** [comment]
The compact format looks a lot better!

@martinholmer Would this formatting for the JSON help address your concerns about the verbosity of the ParamTools JSONS vis-a-vis the Tax-Calc parameters class JSON files?

**Comment by martinholmer** [comment]
@jdebacker asked in ParmaTools issue #56:
> @martinholmer Would this formatting for the JSON help address your concerns about the verbosity of the ParamTools JSON vis-a-vis the Tax-Calc parameters class JSON files?

Only a little bit.  My basic problem with the [above example](https://github.com/PSLmodels/ParamTools/issues/56#issue-445486978) is that it should be able to be expressed (as it is in classes derived from the Tax-Calculator Parameters class) using just the first four "year" expressions.

**Comment by hdoupe** [comment]
@martinholmer thanks for your feedback. The redundancy is definitely annoying. Right now, ParamTools can be [extended to provide this functionality][1]. However, it could be added to ParamTools without too much difficulty. This is the information that is needed to implement parameter value extension:

1. which label should be extended (e.g. "year")
2. what is the step size (e.g. 1)
3. what are the minimum and maximum values for the label (e.g. 2013 and 2027)

ParamTools already has 2 and 3. The label to extend is the only new piece of information that is required. I'll take a look at polishing up and generalizing the approach I used in the example I linked to above.


[1]: https://nbviewer.jupyter.org/github/PSLmodels/ParamTools/blob/4cf2ee289daaec9161eefb7cd666145d771aa14e/paramtools/examples/taxparams/IndexedParametersEx.ipynb#Extend-Parameters

**Comment by hdoupe** [comment]
@jdebacker @martinholmer the parameter array extension capability is in ParamTools 0.6.0. I'll keep this issue open while I look at other ways to make the JSON format more compact.

**Comment by hdoupe** [comment]
Closing #56. It would be nice to print some parts of the JSON format more concisely. However, this is a low priority goal. I'm happy to revisit if anyone is interested in some kind of compact version of default JSON print format from the Python `json` module.
