### ISSUE TITLE
Validate parameters with conditional logic

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/ParamTools#64]
It would be useful if ParamTools validator objects were able to accept conditional logic based on another parameter's value. Using Tax-Cruncher as an example, if marital status is "Single," spouse wages should be restricted to 0.

**Comment by hdoupe** [comment]
@Peter-Metz that would be useful. What do you think about specifying the validator like this:

```json
"swages": {
    "title": "Wage and salary income of spouse",
    "description": "Include self-employment",
    "type": "float",
    "value": 0,
    "validators": {
        "range": {
            "min": 0,
            "max": 9e+99
        },
        "range_conditional_on_parameter_value": [
            {
                "parameter": "marital_status",
                "value": "single",
                "max": 0
            }
        ]
    }
},
```

The "range_on_conditional_parameter_value" would be run in addition to the "range" validator. The "range_conditional_on_parameter_value" checks that the value of "swages" is less than 0 when "marital_status" is "single".

I thought about packing this info into the "range" validator like this:
```json
"range": {
    "min": 0,
    "max": [{"value": 9e+99}, {"marital_status": "single", "value":0}]
}
```

But it seems like it would be more straight forward to create a new validator. I think it would be helpful to allow ParamTools users to define their own validators one day. I think that this approach is in line with that spirit.

What do you think about this? I'm open to ideas for shortening this validator's name and making the spec for it more concise/intuitive.

**Comment by Peter-Metz** [comment]
@hdoupe thanks for looking into this. This approach seems reasonable to me. I agree that a new validator is better than packing this logic into the existing range validator.

**Comment by hdoupe** [comment]
No problem. I'll take a shot at this over the next couple weeks.

**Comment by hdoupe** [comment]
#64 is finally closed! Thanks for the idea @Peter-Metz. Please let me know if you run into any bugs/have feedback.
